#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Execute project linters.
"
}

EC_EXCLUDE="(__pycache__|.git|.coverage|coverage.xml|.*\.egg-info|.mypy_cache|.tif|.tiff|.npy|.ipynb|.hdr|.json)"

DIRS_TO_CHECK=("src" "tests" "scripts")

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Text formatting
        echo "Running ec"
        ec --exclude "$EC_EXCLUDE"
        # Sort imports
        echo "Running isort"
        isort --check .
        # Code formatting
        echo "Running yapf"
        yapf -dpr ${DIRS_TO_CHECK[@]}
        # Lint
        echo "Running flake8"
        flake8 ${DIRS_TO_CHECK[@]}
        # Type checking
        echo "Running mypy"
        mypy src
    fi
fi
